
// ----------------------------------------------------------------------

export const PATH_PAGE = {
  comingSoon: '/coming-soon',
  maintenance: '/maintenance',
  pricing: '/pricing',
  payment: '/payment',
  about: '/hakkimizda',
  contact: '/iletisim',
  vendor: '/bayilik-basvurusu',
  faqs: '/faqs',
  gallery: '/galeri',
  video: '/video',
  pdf: '/brosur',
  priceListPdf: '/fiyat-listesi',
  ourprojects: '/projelerimiz',
  mediaPic: '/yazili-basin',
  mediaPicDetail: '/yazili-basin-detay',
  mediaVideo: '/gorsel-basin',
  page404: '/404',
  page500: '/500',
  components: '/components',
  smartCapillarity: '/smart-capillarity',
  smartRoot: '/smart-root',
  smartWaterlevel: '/smart-waterlevel',
  smartFarm: '/smart-farm',
  smartValves: '/smart-valves',
  airMoles:'/air-moles',
  moles:'/smartmoles',
  career :'/kariyer',
};
