// ----------------------------------------------------------------------

export const photos = [
    {id:'1', categoryId:'growtech-fuari', src: '/static/images/growtech/growtech-fuar-smartmoles-1.jpg', alt: 'Growtech Fuari' },
    {id:'2', categoryId:'growtech-fuari', src: '/static/images/growtech/Growtech-4.jpg', alt: 'Growtech Fuari' },
    {id:'3', categoryId:'growtech-fuari', src: '/static/images/growtech/Growtech-2.jpg', alt: 'Growtech Fuari' },
    {id:'4', categoryId:'growtech-fuari', src: '/static/images/growtech/growtech-fuar-smartmoles-2.jpg', alt: 'Growtech Fuari' },
    {id:'5', categoryId:'growtech-fuari', src: '/static/images/growtech/growtech-fuar-smartmoles-3.jpg', alt: 'Growtech Fuari' },
    {id:'6', categoryId:'growtech-fuari', src: '/static/images/growtech/growtech-fuar-smartmoles-4.jpg', alt: 'Growtech Fuari' },
    {id:'7', categoryId:'growtech-fuari', src: '/static/images/growtech/growtech-fuar-smartmoles-5.jpg', alt: 'Growtech Fuari' },
    {id:'8', categoryId:'growtech-fuari', src: '/static/images/growtech/growtech-fuar-smartmoles-6.jpg', alt: 'Growtech Fuari' },
    {id:'9', categoryId:'growtech-fuari', src: '/static/images/growtech/growtech-fuar-smartmoles-7.jpg', alt: 'Growtech Fuari' },
    {id:'10', categoryId:'growtech-fuari', src: '/static/images/growtech/growtech-fuar-smartmoles-8.jpg', alt: 'Growtech Fuari' },
    {id:'11', categoryId:'growtech-fuari', src: '/static/images/growtech/growtech-fuar-smartmoles-9.jpg', alt: 'Growtech Fuari' },
    {id:'12', categoryId:'growtech-fuari', src: '/static/images/growtech/growtech-fuar-smartmoles-10.jpg', alt: 'Growtech Fuari' },
    {id:'13', categoryId:'growtech-fuari', src: '/static/images/growtech/growtech-fuar-smartmoles-11.jpg', alt: 'Growtech Fuari' },
    {id:'14', categoryId:'growtech-fuari', src: '/static/images/growtech/growtech-fuar-smartmoles-12.jpg', alt: 'Growtech Fuari' },
    {id:'15', categoryId:'growtech-fuari', src: '/static/images/growtech/growtech-fuar-smartmoles-13.jpg', alt: 'Growtech Fuari' },
    {id:'16', categoryId:'seralar', src: '/static/images/greenhouse/1.jpg', alt: 'Seralar' },
    {id:'17', categoryId:'seralar', src: '/static/images/greenhouse/2.jpg', alt: 'Seralar' },
    {id:'18', categoryId:'seralar', src: '/static/images/greenhouse/3.jpg', alt: 'Seralar' },
    {id:'19', categoryId:'seralar', src: '/static/images/greenhouse/4.jpg', alt: 'Seralar' },
    {id:'20', categoryId:'peyzaj-alanlari', src: '/static/images/peysage/1.jpg', alt: 'Peyzaj Alanları' },
    {id:'21', categoryId:'peyzaj-alanlari', src: '/static/images/peysage/2.jpg', alt: 'Peyzaj Alanları' },
    {id:'22', categoryId:'peyzaj-alanlari', src: '/static/images/peysage/3.jpg', alt: 'Peyzaj Alanları' },
    {id:'23', categoryId:'peyzaj-alanlari', src: '/static/images/peysage/5.jpg', alt: 'Peyzaj Alanları' },
    {id:'24', categoryId:'peyzaj-alanlari', src: '/static/images/peysage/6.jpg', alt: 'Peyzaj Alanları' },
    {id:'25', categoryId:'tarim-alanlari', src: '/static/images/farm/0b9fcebc-8484-4a85-b69c-7c453e790d8c.jpg', alt: 'Tarım Alanları' },
    {id:'26', categoryId:'tarim-alanlari', src: '/static/images/farm/1.jpg', alt: 'Tarım Alanları' },
    {id:'27', categoryId:'tarim-alanlari', src: '/static/images/farm/1e264d5c-d590-4cb4-849e-34426a85dc2d.jpg', alt: 'Tarım Alanları' },
    {id:'28', categoryId:'tarim-alanlari', src: '/static/images/farm/1f5d8a3a-602a-4981-8102-e6d56fe1c070.jpg', alt: 'Tarım Alanları' },
    {id:'29', categoryId:'tarim-alanlari', src: '/static/images/farm/2.jpg', alt: 'Tarım Alanları' },
    {id:'30', categoryId:'tarim-alanlari', src: '/static/images/farm/3.jpg', alt: 'Tarım Alanları' },
    {id:'31', categoryId:'tarim-alanlari', src: '/static/images/farm/4.jpg', alt: 'Tarım Alanları' },
    {id:'32', categoryId:'tarim-alanlari', src: '/static/images/farm/5.jpg', alt: 'Tarım Alanları' },
    {id:'33', categoryId:'tarim-alanlari', src: '/static/images/farm/57a5c5df-9b53-4e08-a633-f5d66ebe7b47.jpg', alt: 'Tarım Alanları' },
    {id:'34', categoryId:'tarim-alanlari', src: '/static/images/farm/78ef4885-e9ca-4d6c-8ec0-308e51ed7f06.jpg', alt: 'Tarım Alanları' },
    {id:'35', categoryId:'tarim-alanlari', src: '/static/images/farm/12210af1-8e2c-41a7-a534-4eee30ebc97c.jpg', alt: 'Tarım Alanları' },
    {id:'36', categoryId:'tarim-alanlari', src: '/static/images/farm/0599355d-5ae2-42b4-af79-819c5e2167ac.jpg', alt: 'Tarım Alanları' },
    {id:'37', categoryId:'tarim-alanlari', src: '/static/images/farm/20210908_104214.jpg', alt: 'Tarım Alanları' },
    {id:'38', categoryId:'tarim-alanlari', src: '/static/images/farm/20210908_104311.jpg', alt: 'Tarım Alanları' },
    {id:'39', categoryId:'tarim-alanlari', src: '/static/images/farm/d04d4f13-43d0-44e9-8d06-c631bff8654c.jpg', alt: 'Tarım Alanları' },
    {id:'40', categoryId:'tarim-alanlari', src: '/static/images/farm/IMG_2086.jpg', alt: 'Tarım Alanları' },
    {id:'41', categoryId:'tarim-alanlari', src: '/static/images/farm/IMG_6655.jpg', alt: 'Tarım Alanları' },
    {id:'42', categoryId:'tarim-alanlari', src: '/static/images/farm/IMG_6656.jpg', alt: 'Tarım Alanları' },
    {id:'43', categoryId:'tarim-alanlari', src: '/static/images/farm/IMG_6657.jpg', alt: 'Tarım Alanları' },
    {id:'44', categoryId:'tarim-alanlari', src: '/static/images/farm/IMG-20210916-WA0040.jpg', alt: 'Tarım Alanları' },
    {id:'45', categoryId:'tarim-alanlari', src: '/static/images/farm/IMG-20210916-WA0041.jpg', alt: 'Tarım Alanları' },
    {id:'46', categoryId:'tarim-alanlari', src: '/static/images/farm/smartmoles.jpg', alt: 'Tarım Alanları' },
    {id:'47', categoryId:'tarim-alanlari', src: '/static/images/farm/smartmoles-1.jpg', alt: 'Tarım Alanları' },
    {id:'48', categoryId:'tarim-alanlari', src: '/static/images/farm/smartmoles-2.jpg', alt: 'Tarım Alanları' },
    {id:'49', categoryId:'tarim-alanlari', src: '/static/images/farm/smartmoles-5.jpg', alt: 'Tarım Alanları' },
    {id:'50', categoryId:'tarim-alanlari', src: '/static/images/farm/smartmoles-6.jpg', alt: 'Tarım Alanları' },
    {id:'51', categoryId:'tarim-alanlari', src: '/static/images/farm/smartmoles-aycicegi.jpg', alt: 'Tarım Alanları' },
    {id:'52', categoryId:'tarim-alanlari', src: '/static/images/farm/farm01.jpeg', alt: 'Tarım Alanları' },
    {id:'53', categoryId:'tarim-alanlari', src: '/static/images/farm/farm00.jpeg', alt: 'Tarım Alanları' },

    {id:'54', categoryId:'aycicegi', src: '/static/images/aycicegi/aycicegi1.jpg', alt: 'Tarım Alanları' },
    {id:'55', categoryId:'aycicegi', src: '/static/images/aycicegi/aycicegi2.jpg', alt: 'Tarım Alanları' },

    {id:'56', categoryId:'bag', src: '/static/images/bag/bag01.jpg', alt: 'Tarım Alanları' },
    {id:'57', categoryId:'bag', src: '/static/images/bag/bag02.jpg', alt: 'Tarım Alanları' },
    {id:'58', categoryId:'bag', src: '/static/images/bag/bag03.jpg', alt: 'Tarım Alanları' },
    {id:'59', categoryId:'bag', src: '/static/images/bag/bag04.jpg', alt: 'Tarım Alanları' },
    {id:'60', categoryId:'bag', src: '/static/images/bag/bag05.jpg', alt: 'Tarım Alanları' },

    {id:'61', categoryId:'ceviz', src: '/static/images/ceviz/ceviz1.jpg', alt: 'Tarım Alanları' },
    {id:'62', categoryId:'ceviz', src: '/static/images/ceviz/ceviz2.jpg', alt: 'Tarım Alanları' },
    {id:'63', categoryId:'ceviz', src: '/static/images/ceviz/ceviz3.jpg', alt: 'Tarım Alanları' },
    {id:'64', categoryId:'ceviz', src: '/static/images/ceviz/ceviz4.jpg', alt: 'Tarım Alanları' },
    {id:'83', categoryId:'ceviz', src: '/static/images/ceviz/cevizpompa.jpg', alt: 'Tarım Alanları' },
    {id:'111', categoryId:'ceviz', src: '/static/images/ceviz/ceviz028.jpg', alt: 'Tarım Alanları' },
    {id:'112', categoryId:'ceviz', src: '/static/images/ceviz/ceviz029.jpg', alt: 'Tarım Alanları' },
    {id:'113', categoryId:'ceviz', src: '/static/images/ceviz/ceviz030.jpg', alt: 'Tarım Alanları' },
    {id:'114', categoryId:'ceviz', src: '/static/images/ceviz/ceviz031.jpg', alt: 'Tarım Alanları' },
    {id:'127', categoryId:'ceviz', src: '/static/images/ceviz/ceviz5.jpg', alt: 'Tarım Alanları' },

    {id:'65', categoryId:'cim', src: '/static/images/cim/cim01.jpg', alt: 'Tarım Alanları' },
    {id:'66', categoryId:'cim', src: '/static/images/cim/cim02.jpg', alt: 'Tarım Alanları' },

    {id:'67', categoryId:'elma', src: '/static/images/elma/elm1.jpg', alt: 'Tarım Alanları' },
    {id:'68', categoryId:'elma', src: '/static/images/elma/elm2.jpg', alt: 'Tarım Alanları' },

    {id:'69', categoryId:'hurma', src: '/static/images/hurma/hurma001.jpg', alt: 'Tarım Alanları' },
    {id:'70', categoryId:'hurma', src: '/static/images/hurma/hurma002.jpg', alt: 'Tarım Alanları' },
    {id:'71', categoryId:'hurma', src: '/static/images/hurma/hurma003.jpg', alt: 'Tarım Alanları' },
    {id:'72', categoryId:'hurma', src: '/static/images/hurma/hurma004.jpg', alt: 'Tarım Alanları' },
    {id:'73', categoryId:'hurma', src: '/static/images/hurma/hurma005.jpg', alt: 'Tarım Alanları' },
    {id:'74', categoryId:'hurma', src: '/static/images/hurma/hurma006.jpg', alt: 'Tarım Alanları' },
    {id:'75', categoryId:'hurma', src: '/static/images/hurma/hurma007.jpg', alt: 'Tarım Alanları' },
    {id:'76', categoryId:'hurma', src: '/static/images/hurma/hurma008.jpg', alt: 'Tarım Alanları' },
    {id:'77', categoryId:'hurma', src: '/static/images/hurma/hurma009.jpg', alt: 'Tarım Alanları' },
    {id:'78', categoryId:'hurma', src: '/static/images/hurma/hurma010.jpg', alt: 'Tarım Alanları' },
    {id:'79', categoryId:'hurma', src: '/static/images/hurma/hurma011.jpg', alt: 'Tarım Alanları' },
    {id:'80', categoryId:'hurma', src: '/static/images/hurma/hurma012.jpg', alt: 'Tarım Alanları' },
    {id:'81', categoryId:'hurma', src: '/static/images/hurma/hurma013.jpg', alt: 'Tarım Alanları' },
    {id:'82', categoryId:'hurma', src: '/static/images/hurma/hurma014.jpg', alt: 'Tarım Alanları' },

    {id:'84', categoryId:'kiraz', src: '/static/images/kiraz/kiraz001.jpg', alt: 'Tarım Alanları' },
    {id:'85', categoryId:'kiraz', src: '/static/images/kiraz/kiraz002.jpg', alt: 'Tarım Alanları' },
    {id:'86', categoryId:'kiraz', src: '/static/images/kiraz/kiraz003.jpg', alt: 'Tarım Alanları' },
    {id:'87', categoryId:'kiraz', src: '/static/images/kiraz/kiraz004.jpg', alt: 'Tarım Alanları' },
    {id:'88', categoryId:'kiraz', src: '/static/images/kiraz/kiraz005.jpg', alt: 'Tarım Alanları' },
    {id:'89', categoryId:'kiraz', src: '/static/images/kiraz/kiraz006.jpg', alt: 'Tarım Alanları' },
    {id:'90', categoryId:'kiraz', src: '/static/images/kiraz/kiraz007.jpg', alt: 'Tarım Alanları' },
    {id:'91', categoryId:'kiraz', src: '/static/images/kiraz/kiraz008.jpg', alt: 'Tarım Alanları' },
    {id:'92', categoryId:'kiraz', src: '/static/images/kiraz/kiraz009.jpg', alt: 'Tarım Alanları' },
    {id:'93', categoryId:'kiraz', src: '/static/images/kiraz/kiraz010.jpg', alt: 'Tarım Alanları' },
    {id:'94', categoryId:'kiraz', src: '/static/images/kiraz/kiraz011.jpg', alt: 'Tarım Alanları' },
    {id:'95', categoryId:'kiraz', src: '/static/images/kiraz/kiraz012.jpg', alt: 'Tarım Alanları' },
    {id:'96', categoryId:'kiraz', src: '/static/images/kiraz/kiraz013.jpg', alt: 'Tarım Alanları' },
    {id:'97', categoryId:'kiraz', src: '/static/images/kiraz/kiraz014.jpg', alt: 'Tarım Alanları' },
    {id:'98', categoryId:'kiraz', src: '/static/images/kiraz/kiraz015.jpg', alt: 'Tarım Alanları' },
    {id:'99', categoryId:'kiraz', src: '/static/images/kiraz/kiraz016.jpg', alt: 'Tarım Alanları' },
    {id:'100', categoryId:'kiraz', src: '/static/images/kiraz/kiraz017.jpg', alt: 'Tarım Alanları' },
    {id:'101', categoryId:'kiraz', src: '/static/images/kiraz/kiraz018.jpg', alt: 'Tarım Alanları' },
    {id:'102', categoryId:'kiraz', src: '/static/images/kiraz/kiraz019.jpg', alt: 'Tarım Alanları' },
    {id:'103', categoryId:'kiraz', src: '/static/images/kiraz/kiraz020.jpg', alt: 'Tarım Alanları' },
    {id:'104', categoryId:'kiraz', src: '/static/images/kiraz/kiraz021.jpg', alt: 'Tarım Alanları' },
    {id:'105', categoryId:'kiraz', src: '/static/images/kiraz/kiraz022.jpg', alt: 'Tarım Alanları' },
    {id:'106', categoryId:'kiraz', src: '/static/images/kiraz/kiraz023.jpg', alt: 'Tarım Alanları' },
    {id:'107', categoryId:'kiraz', src: '/static/images/kiraz/kiraz024.jpg', alt: 'Tarım Alanları' },
    {id:'108', categoryId:'kiraz', src: '/static/images/kiraz/kiraz025.jpg', alt: 'Tarım Alanları' },
    {id:'109', categoryId:'kiraz', src: '/static/images/kiraz/kiraz026.jpg', alt: 'Tarım Alanları' },
    {id:'110', categoryId:'kiraz', src: '/static/images/kiraz/kiraz027.jpg', alt: 'Tarım Alanları' },
    {id:'115', categoryId:'kiraz', src: '/static/images/kiraz/kiraz032.jpg', alt: 'Tarım Alanları' },
    {id:'116', categoryId:'kiraz', src: '/static/images/kiraz/kiraz033.jpg', alt: 'Tarım Alanları' },

    {id:'117', categoryId:'leylandi', src: '/static/images/leylandi/leylandi.jpg', alt: 'Tarım Alanları' },

    {id:'118', categoryId:'misir', src: '/static/images/misir/misir1.jpg', alt: 'Tarım Alanları' },
    {id:'119', categoryId:'misir', src: '/static/images/misir/misir2.jpg', alt: 'Tarım Alanları' },
    {id:'120', categoryId:'misir', src: '/static/images/misir/misir3.jpg', alt: 'Tarım Alanları' },

    {id:'121', categoryId:'muz', src: '/static/images/muz/muz1.jpg', alt: 'Tarım Alanları' },
    {id:'128', categoryId:'muz', src: '/static/images/muz/muz2.jpg', alt: 'Tarım Alanları' },
    {id:'129', categoryId:'muz', src: '/static/images/muz/muz3.jpg', alt: 'Tarım Alanları' },
    {id:'130', categoryId:'muz', src: '/static/images/muz/muz4.jpg', alt: 'Tarım Alanları' },
    {id:'131', categoryId:'muz', src: '/static/images/muz/muz5.jpg', alt: 'Tarım Alanları' },
    {id:'132', categoryId:'muz', src: '/static/images/muz/muz6.jpg', alt: 'Tarım Alanları' },
    {id:'133', categoryId:'muz', src: '/static/images/muz/muz7.jpg', alt: 'Tarım Alanları' },

    {id:'122', categoryId:'yonca', src: '/static/images/yonca/yonca01.jpg', alt: 'Tarım Alanları' },
    {id:'123', categoryId:'yonca', src: '/static/images/yonca/yonca02.jpg', alt: 'Tarım Alanları' },

    {id:'124', categoryId:'zeytin', src: '/static/images/zeytin/zeytin01.jpg', alt: 'Tarım Alanları' },
    {id:'125', categoryId:'zeytin', src: '/static/images/zeytin/zeytin02.jpg', alt: 'Tarım Alanları' },
    {id:'126', categoryId:'zeytin', src: '/static/images/zeytin/zeytin03.jpg', alt: 'Tarım Alanları' },














];